config/routes.rb
SampleApp::Application.routes.draw do
  resources :users, :teams
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/standings', to: 'teams#standings',      via: 'get'
  match '/shield',    to: 'teams#shield',         via: 'get'
  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/help',      to: 'static_pages#help',    via: 'get'
  match '/about',     to: 'static_pages#about',   via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'

  

end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save {self.email = email.downcase}
	before_create :create_remember_token
	validates :name,  presence: true, length: {maximum: 50}
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, 
					uniqueness: {case_sensitive: false}
	has_secure_password
	  validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :parse_xml, only: [:standings]
  before_action :parse_xml2, only: [:shield]
  helper_method :sort_column, :sort_direction
  
  def standings
    @teams = Team.order(sort_column + " " + sort_direction)
  end

  def parse_xml
  	  @doc = Nokogiri::XML(File.open("srml-98-2013-standings.xml"))

	  teamRef = @doc.xpath("//@TeamRef")
	  points = @doc.xpath("//Points")
	  played = @doc.xpath("//Played")
	  won = @doc.xpath("//Won")
	  lost = @doc.xpath("//Lost")
	  ties = @doc.xpath("//Drawn")
	  goalsFor = @doc.xpath("//For")
	  goalsAgainst = @doc.xpath("//Against")
	  homeFor = @doc.xpath("//HomeFor")
	  homeAgainst = @doc.xpath("//HomeAgainst")
	  awayFor = @doc.xpath("//AwayFor")
	  awayAgainst = @doc.xpath("//AwayAgainst")

	def getName(nRef)
	    name = @doc.xpath("//Team[@uID='"+nRef+"']/Name")
	    name[0].content.to_s
  	end

  	@confs = {eastern: [], western: []}

	(0...teamRef.length).each do |i|
		if i<10
		@confs[:eastern] << {
			getName(teamRef[i]).parameterize.underscore.to_sym => {
			id: i+1, 
			name: getName(teamRef[i]).to_s,
			points: points[i].content.to_f, 
		  	played: played[i].content.to_f,
		  	won: won[i].content.to_i,
		  	lost: lost[i].content.to_i,
		  	ties: ties[i].content.to_i,
		  	gFor: goalsFor[i].content.to_i,
		  	gAgt: goalsAgainst[i].content.to_i,
		  	homeFor: homeFor[i].content.to_i,
		  	homeAgt: homeAgainst[i].content.to_i,
		  	awayFor: awayFor[i].content.to_i,
		  	awayAgt: awayAgainst[i].content.to_i
	  	 	}
	  	}
	    else 
			@confs[:western] << {
			getName(teamRef[i]).parameterize.underscore.to_sym => { 
			id: i-9,
			name: getName(teamRef[i]).to_s,
			points: points[i].content.to_f, 
		  	played: played[i].content.to_f,
		  	won: won[i].content.to_i,
		  	lost: lost[i].content.to_i,
		  	ties: ties[i].content.to_i,
		  	gFor: goalsFor[i].content.to_i,
		  	gAgt: goalsAgainst[i].content.to_i,
		  	homeFor: homeFor[i].content.to_i,
		  	homeAgt: homeAgainst[i].content.to_i,
		  	awayFor: awayFor[i].content.to_i,
		  	awayAgt: awayAgainst[i].content.to_i
	  	 	}
	  	}
	  end
	end


@magicNoE=0 
@magicNoW=0 

@confs.each do |key, value| 
  value.each do |l, m| 
    l.each do |k,v| 
      if v[:id]==6 && key==:eastern 
        @magicNoE = v[:points]+((34-v[:played])*3) 
      elsif v[:id]==6 && key==:western 
        @magicNoW = v[:points]+((34-v[:played])*3) 
      end
    end
  end
end

  end

  def parse_xml2
  	@doc = Nokogiri::XML(File.open("srml-98-2013-standings.xml"))

	  teamRef = @doc.xpath("//@TeamRef")
	  points = @doc.xpath("//Points")
	  played = @doc.xpath("//Played")
	  won = @doc.xpath("//Won")
	  lost = @doc.xpath("//Lost")
	  ties = @doc.xpath("//Drawn")
	  goalsFor = @doc.xpath("//For")
	  goalsAgainst = @doc.xpath("//Against")
	  homeFor = @doc.xpath("//HomeFor")
	  homeAgainst = @doc.xpath("//HomeAgainst")
	  awayFor = @doc.xpath("//AwayFor")
	  awayAgainst = @doc.xpath("//AwayAgainst")

	def getName(nRef)
	    name = @doc.xpath("//Team[@uID='"+nRef+"']/Name")
	    name[0].content.to_s
  	end

  	@confs = {teams: []}

  		(0...teamRef.length).each do |i|
		@confs[:teams] << {
			getName(teamRef[i]).parameterize.underscore.to_sym => {
			id: i+1, 
			name: getName(teamRef[i]).to_s,
			points: points[i].content.to_f, 
		  	played: played[i].content.to_f,
		  	won: won[i].content.to_i,
		  	lost: lost[i].content.to_i,
		  	ties: ties[i].content.to_i,
		  	gFor: goalsFor[i].content.to_i,
		  	gAgt: goalsAgainst[i].content.to_i,
		  	homeFor: homeFor[i].content.to_i,
		  	homeAgt: homeAgainst[i].content.to_i,
		  	awayFor: awayFor[i].content.to_i,
		  	awayAgt: awayAgainst[i].content.to_i
	  	 	}
	  	}
	  	end
  end

  private
  
  def sort_column
    Team.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
helper_method :sort_column, :sort_direction
  
  def index
    @users = User.order(sort_column + " " + sort_direction)
  end
  
  # ...
  
  private
  
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def sortable(column, title = nil)
  		title ||= column.titleize
  		css_class = column == sort_column ? "current #{sort_direction}" : nil
  		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  		link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper

	

end

app/helpers/users_helper.rb
module UsersHelper

	#returns gravatar for the given user
	def gravatar_for(user, options = { size: 50})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
			  <%= link_to "sample app", root_path, id: "logo" %>
            </div>
        </div>
    </header>

app/views/layouts/_shim.html.erb
  		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Sample App</title>
  		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  		<%= csrf_meta_tags %>
  		<%= render 'layouts/shim' %>
	</head>
	<body>
	<%= render 'layouts/header' %>
    <div class="container">
    	<% flash.each do |key, value| %>
    		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
    	<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, 'About Us' %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the MLS App</h1>

  <h2>
    This is the home page for Amer Shalan's sample app for the MLS coding challenge.
  </h2>

  <%= link_to "Standings!", standings_path, class: "btn btn-large btn-primary" %>

 <%= link_to "Supporter's Shield Race!", shield_path, class: "btn btn-large btn-primary" %>
  
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>


<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<%end%>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
	  <h1>
		<%= gravatar_for @user %>
		<%= @user.name %>
	  </h1>
	</section>
  </aside>
</div>